## HOW TO RUN: ##
#
# make reload ENV=dev
#

services:

  postgis:
    restart: "no" # disable autorestart
    volumes:
      - g3wsuite-pg-data:/var/lib/postgresql
    networks:
      internal:

  g3w-suite:
    environment:
      - BITBUCKET_TOKEN
      - G3WSUITE_DEBUG=True
      - G3WSUITE_GUNICORN_NUM_WORKERS=${G3WSUITE_GUNICORN_NUM_WORKERS:-1}
      - WEBGIS_PUBLIC_HOSTNAME=${WEBGIS_PUBLIC_HOSTNAME:-localhost}
      - WEBGIS_ADMIN_EMAIL=${WEBGIS_ADMIN_EMAIL:-info@gis3w.it}
      # HOTFIX: for Python 11: https://stackoverflow.com/a/76469774
      - PIP_BREAK_SYSTEM_PACKAGES=1
      - PIP_ROOT_USER_ACTION=ignore
      # HOTFIX: for Ubuntu Jammy: https://github.com/pypa/setuptools/issues/3269#issuecomment-1254507377
      - DEB_PYTHON_INSTALL_LAYOUT=deb_system
      # HOTFIX: for git ownership issues
      - GIT_CONFIG_PARAMETERS='safe.directory=/code'
    stdin_open: true
    tty: true

    ports:
      - "8000:8000" # g3w-suite
      - "5678:5678" # debugpy
    restart: "no" # disable autorestart
    volumes:
      - ./scripts:/scripts
      - ${G3WSUITE_LOCAL_CODE_PATH}:/code

  g3w-suite-consumer:
    deploy:
      replicas: 1  # 0 = disable g3w-suite-consumer service
    environment:
      - BITBUCKET_TOKEN
      - G3WSUITE_DEBUG=True
      - G3WSUITE_GUNICORN_NUM_WORKERS=${G3WSUITE_GUNICORN_NUM_WORKERS:-1}
      - G3WSUITE_GUNICORN_TIMEOUT=${G3WSUITE_GUNICORN_TIMEOUT:-3600}
      - WEBGIS_PUBLIC_HOSTNAME=${WEBGIS_PUBLIC_HOSTNAME:-localhost}
      - WEBGIS_ADMIN_EMAIL=${WEBGIS_ADMIN_EMAIL:-info@gis3w.it}
      # HOTFIX: for Python 11: https://stackoverflow.com/a/76469774
      - PIP_BREAK_SYSTEM_PACKAGES=1
      - PIP_ROOT_USER_ACTION=ignore
      # HOTFIX: for Ubuntu Jammy: https://github.com/pypa/setuptools/issues/3269#issuecomment-1254507377
      - DEB_PYTHON_INSTALL_LAYOUT=deb_system
      # HOTFIX: for git ownership issues
      - GIT_CONFIG_PARAMETERS='safe.directory=/code'
    stdin_open: true
    tty: true
    restart: "no" # disable autorestart
    volumes:
      - ./scripts:/scripts
      - ${G3WSUITE_LOCAL_CODE_PATH}:/code

  nginx:
    deploy:
      replicas: 1  # 0 = disable nginx service

  certbot:
    deploy:
      replicas: 1  # 0 = disable certbot service

volumes:
  shared-volume:
  g3wsuite-pg-data:

networks:
  internal:
