## HOW TO RUN: ##
#
# make reload ENV=dev
#

x-g3w-suite: &g3w-suite
  restart: "no"
  image: g3wsuite/g3w-suite:dev
  environment:
    - BITBUCKET_TOKEN
    - G3WSUITE_DEBUG=True
    - PIP_BREAK_SYSTEM_PACKAGES=1
    - PIP_ROOT_USER_ACTION=ignore
    - DEB_PYTHON_INSTALL_LAYOUT=deb_system
    - GIT_CONFIG_PARAMETERS='safe.directory=*'
  volumes:
    - ./scripts:/scripts
    - ${G3WSUITE_LOCAL_CODE_PATH}:/code

services:

  postgis:
    restart: "no" # disable autorestart
    volumes:
      - ${WEBGIS_DOCKER_SHARED_VOLUME}:/var/lib/postgresql

  g3w-suite:
    <<: *g3w-suite
    ports:
      - "8000:8000" # g3w-suite
      - "5678:5678" # debugpy

  g3w-suite-consumer:
    <<: *g3w-suite
    deploy:
      replicas: 1  # 0 = disable service

volumes:
  shared-volume:
  g3wsuite-pg-data:

networks:
  internal:
