## HOW TO RUN: ##
#
# docker compose -f docker-compose.yml -f docker-compose-dev.yml up -d
#
version: "3.4"
services:

  postgis:
    restart: "no" # disable autorestart
    volumes:
      - g3wsuite-pg-data:/var/lib/postgresql
    networks:
      internal:
        aliases:
          - ${WEBGIS_PUBLIC_HOSTNAME}

  g3w-suite:
    environment:
      - BITBUCKET_TOKEN
      - G3WSUITE_DEBUG=${G3WSUITE_DEBUG:-True}
      - G3WSUITE_GUNICORN_NUM_WORKERS=${G3WSUITE_GUNICORN_NUM_WORKERS:-1}
      - G3WSUITE_QDJANGO_SERVER_URL
    ports:
      - "8000:8000"
    restart: "no" # disable autorestart
    volumes:
      - ./scripts:/scripts
      - ${G3WSUITE_LOCAL_CODE_PATH}:/code
    entrypoint: /scripts/docker-entrypoint.sh

  redis:
    deploy:
      replicas: 0  # disable redis service

  nginx:
    deploy:
      replicas: 0  # disable nginx service

  certbot:
    deploy:
      replicas: 0  # disable certbot service

  g3w-suite-consumer:
    deploy:
      replicas: 0  # disable huey service

volumes:
  shared-volume:
  g3wsuite-pg-data:

networks:
  internal:
