# Used solely for docker-compose build
version: '3.9'
services:
  g3wsuite-base:
    image: g3wsuite/g3w-suite-deps-ltr:dev
    build:
      context: .
      dockerfile: Dockerfile.g3wsuite.dockerfile
      # Use yaml anchor for reusability
      args: &build-args-anchor
        DISTRO: ${DISTRO}
        IMAGE_VERSION: ${IMAGE_VERSION}
        QGIS_LTR: ${QGIS_LTR}
        INSTALL_MSSQL: ${INSTALL_MSSQL}
      target: g3w-suite-base

  g3wsuite-prod:
    image: g3wsuite/g3w-suite:dev
    build:
      context: .
      dockerfile: Dockerfile.g3wsuite.dockerfile
      args:
        <<: *build-args-anchor
      target: g3w-suite-prod

