## HOW TO RUN: ##
#
# make dev  reload  (for development → `g3wsuite/g3w-suite:next`)
# make prod reload  (for production  → `g3wsuite/g3w-suite:<current_branch>`)
#

x-g3w-suite: &g3w-suite
  build:
    context: ./
    target: suite
  image: g3wsuite/g3w-suite:${DEV_IMAGE:-dev}
  restart: "${RESTART_POLICY:-on-failure}"
  cap_add:
    - ${SYS_PTRACE:-NET_BIND_SERVICE} # DEV MODE: allow "sys_ptrace" 
  environment:
    - BITBUCKET_TOKEN
    - DEV_MODE=${DEV_MODE:-False}
    - FRONTEND
    - G3WSUITE_ADMIN_USERNAME
    - G3WSUITE_ADMIN_PASSWORD
    - G3WSUITE_DEBUG=${G3WSUITE_DEBUG:-False}
    - G3WSUITE_GUNICORN_MAX_REQUESTS
    - G3WSUITE_GUNICORN_NUM_WORKERS=${G3WSUITE_GUNICORN_NUM_WORKERS:-1}
    - G3WSUITE_GUNICORN_TIMEOUT=${G3WSUITE_GUNICORN_TIMEOUT:-3600}
    - G3WSUITE_POSTGRES_DBNAME
    - G3WSUITE_POSTGRES_USER
    - G3WSUITE_POSTGRES_USER_LOCAL
    - G3WSUITE_POSTGRES_PASS
    - G3WSUITE_POSTGRES_HOST
    - G3WSUITE_POSTGRES_PORT
    - G3WSUITE_RUN_HUEY
    - G3WSUITE_TILECACHE_PATH
    - PGSERVICEFILE
    - TILESTACHE_CACHE_BUFFER_SIZE
    - TILESTACHE_CACHE_TOKEN
    - WEBGIS_PUBLIC_HOSTNAME=${WEBGIS_PUBLIC_HOSTNAME:-localhost}
    - WEBGIS_ADMIN_EMAIL=${WEBGIS_ADMIN_EMAIL:-info@gis3w.it}
  volumes:
    - ${WEBGIS_DOCKER_SHARED_VOLUME}:/shared-volume
    - ${WEBGIS_DOCKER_SHARED_VOLUME}/node_modules:/code/node_modules
    - ./config/g3w-suite/overrides/static:/code/static:ro
    - ./config/g3w-suite/overrides/templates:/code/templates:ro
    - ./config/g3w-suite/settings_docker.py:/code/g3w-admin/base/settings/local_settings.py
    - ./secrets/pg_service.conf:${PGSERVICEFILE}
    - ./config/qgis/QGIS3.ini:/shared-volume/QGIS/QGIS3.ini
    - "${SCRIPTS_VOLUME:-void:/void}" # DEV MODE: hot reload for "/scripts" folder
    - "${CODE_VOLUME:-void:/void}"    # DEV MODE: hot reload for "/code" folder
    - uv_cache:/root/.cache/uv
  logging: &g3w-suite-logging
    driver: "json-file"
    options:
      max-size: "200k"
      max-file: "10"
  stdin_open: ${DEV_MODE:-false}
  tty: ${DEV_MODE:-false}
  networks:
    internal:

services:

  postgis:
    deploy:
      replicas: 1  # 0 = disable service
    image: kartoza/postgis:16-3.4
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_DBNAME=${G3WSUITE_POSTGRES_DBNAME},data_testing,data_production
      - POSTGRES_USER=${G3WSUITE_POSTGRES_USER_LOCAL}
      - POSTGRES_PASS=${G3WSUITE_POSTGRES_PASS}
      - ALLOW_IP_RANGE=0.0.0.0/0
      - RUN_AS_ROOT=true
      - FORCE_SSL=False
    restart: "${RESTART_POLICY:-on-failure}"
    logging: *g3w-suite-logging
    volumes:
      - ${WEBGIS_DOCKER_SHARED_VOLUME}:/var/lib/postgresql
    healthcheck:
      interval: 60s
      timeout: 30s
      retries: 3
      test: "PGPASSWORD=${G3WSUITE_POSTGRES_PASS} pg_isready -h 127.0.0.1 -U ${G3WSUITE_POSTGRES_USER_LOCAL} -d ${G3WSUITE_POSTGRES_DBNAME}"
    networks:
      internal:
        aliases:
          - ${WEBGIS_PUBLIC_HOSTNAME}

  g3w-suite:
    <<: *g3w-suite
    deploy:
      replicas: 1  # 0 = disable service
    expose:
      - 8000
      - 5678
    entrypoint: /bin/bash -c "G3WSUITE_CONSUMER=1 /scripts/docker-entrypoint.sh"
    depends_on:
      - postgis

  # Asynchronous tasks consumer (run_huey)
  g3w-suite-consumer:
    <<: *g3w-suite
    deploy:
      replicas: 1  # 0 = disable service
    entrypoint: /bin/bash -c "G3WSUITE_CONSUMER=0 /scripts/docker-entrypoint.sh"
    depends_on:
      - g3w-suite
      - redis

  redis:
    deploy:
      replicas: 1  # 0 = disable service
    image: redis:latest
    expose:
      - 6379
    networks:
      internal:
    restart: "${RESTART_POLICY:-on-failure}"

  elasticsearch:
    deploy:
      replicas: 1  # 0 = disable service
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.14
    user: root
    command: >
      bash -c "chown -R 1000:0 /usr/share/elasticsearch/data && exec setpriv --reuid=1000 --regid=0 --init-groups /usr/local/bin/docker-entrypoint.sh elasticsearch"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ${WEBGIS_DOCKER_SHARED_VOLUME}/esdata:/usr/share/elasticsearch/data
    networks:
      internal:

  # PROD SERVER: expose port 8000 (django) and 443 (django)
  nginx:
    deploy:
      replicas: ${PROD_SERVER:-1}  # 0 = disable service
    image: nginx
    environment:
      - WEBGIS_PUBLIC_HOSTNAME
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - ${WEBGIS_DOCKER_SHARED_VOLUME}:/shared-volume
      - ${WEBGIS_DOCKER_SHARED_VOLUME}/var/www/.well-known:/var/www/.well-known
      - ${WEBGIS_DOCKER_SHARED_VOLUME}/certs/letsencrypt:/etc/letsencrypt:ro
      - ./config/g3w-suite/overrides/static:/shared-volume/static/overrides:ro
      - ./config/nginx:/etc/nginx/conf.d/:ro
      - ./config/nginx/html:/var/www/html:ro
    logging: *g3w-suite-logging
    restart: "${RESTART_POLICY:-on-failure}"
    networks:
      internal:

  # DEV SERVER: expose port 8000 (django) and 5678 (debug.py)
  dev-server:
    deploy:
      replicas: ${DEV_SERVER:-0}  # 0 = disable service
    image: alpine/socat
    ports:
      - "8000:8000"
      - "5678:5678"
    entrypoint: >
      /bin/sh -c "
        socat TCP-LISTEN:8000,fork,reuseaddr TCP:g3w-suite:8000 &
        socat TCP-LISTEN:5678,fork,reuseaddr TCP:g3w-suite:5678 &
        wait"
    logging: *g3w-suite-logging
    restart: "${RESTART_POLICY:-on-failure}"
    depends_on:
      - g3w-suite
    networks:
      internal:

volumes:
  shared-volume:
  uv_cache:
  void: # fallback for production (dev mounts)

networks:
  internal: