services:
  # Asynchronous tasks consumer (run_huey)
  g3w-suite-consumer:
    image: g3wsuite/g3w-suite:dev
    environment:
      - DISPLAY=:99
      - G3WSUITE_TILECACHE_PATH
      - G3WSUITE_POSTGRES_DBNAME
      - G3WSUITE_POSTGRES_USER
      - G3WSUITE_POSTGRES_USER_LOCAL
      - G3WSUITE_POSTGRES_PASS
      - G3WSUITE_POSTGRES_HOST
      - G3WSUITE_POSTGRES_PORT
      - G3WSUITE_ORS_API_ENDPOINT
      - G3WSUITE_ORS_API_KEY
      - TILESTACHE_CACHE_BUFFER_SIZE
      - TILESTACHE_CACHE_TOKEN
      - G3WSUITE_GUNICORN_NUM_WORKERS
      - G3WSUITE_GUNICORN_MAX_REQUESTS
      - FRONTEND
      - PGSERVICEFILE
      - QGIS_OPTIONS_PATH=/shared-volume/
      - QGIS_SERVER_LOG_FILE
      - QGIS_SERVER_LOG_LEVEL
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    entrypoint: /scripts/docker-consumer-entrypoint.sh
    depends_on:
      - g3w-suite
      - redis
    volumes:
      - ${WEBGIS_DOCKER_SHARED_VOLUME}:/shared-volume
      - ${WEBGIS_DOCKER_SHARED_VOLUME}/node_modules:/code/node_modules
      - ./config/g3w-suite/overrides/static:/code/static:ro
      - ./config/g3w-suite/overrides/templates:/code/templates:ro
      - ./config/g3w-suite/settings_docker.py:/code/g3w-admin/base/settings/local_settings.py
      - ./secrets/pg_service.conf:${PGSERVICEFILE}
      - ./config/qgis/QGIS3.ini:/shared-volume/QGIS/QGIS3.ini
    networks:
      internal: