name: G3W-SUITE-DOCKER build tests

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-24.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')" >> $GITHUB_ENV
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      -
        name: "Build deps image (stage: deps, QGIS LTR)"
        id: docker_build_deps
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          target: deps
          push: false
          tags: g3wsuite/g3w-suite-deps-ltr:${{ env.BRANCH_NAME }}

      -
        name: Image digest
        run: echo ${{ steps.docker_build_deps.outputs.digest }}

      - name: "Build main image (stage: suite)"
        id: docker_build_main
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          target: suite
          push: false
          tags: g3wsuite/g3w-suite:${{ env.BRANCH_NAME }}
